##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # jenkins
  jenkins:
    image: ${IMAGE_JENKINS}
    container_name: "jenkins.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "jenkins.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    environment:
      - JAVA_OPTS=-XshowSettings:vm -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Duser.timezone=Asia/Shanghai -Djava.util.logging.config.file=/var/jenkins_data/log.properties -Dhudson.footerURL=http://mycompany.com
      - JENKINS_UC=https://mirrors.huaweicloud.com/jenkins/updates/
      - JENKINS_UC_EXPERIMENTAL=https://mirrors.huaweicloud.com/jenkins/updates/experimental/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/bin/docker:/usr/bin/docker:ro
      - ./volume/jenkins/home:/var/jenkins_home:rw
      - ./volume/jenkins/data:/var/jenkins_data:rw
      - ./volume/jenkins/back:/var/jenkins_back:rw
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      mynet:
        ipv4_address: 172.16.100.10
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.100.0/24"