##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # jenkins
  jenkins:
    image: ${IMAGE_NEXUS}
    container_name: "jenkins.${GROUP_NAME}.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "jenkins.${GROUP_NAME}.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    environment:
      - JAVA_OPTS=-Djava.util.logging.config.file=/var/jenkins_home/log.properties
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/jenkins/data:/var/jenkins_home:rw
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      mynet:
        ipv4_address: 172.16.100.10
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.100.0/24"